/**
 * Config File Generator for iMessage Timeline
 *
 * Implements CONFIG--T03: Add Config Generation Command
 * Generates starter configuration files with documentation comments
 */

import { constants } from 'node:fs'
import { access, writeFile } from 'node:fs/promises'

import yaml from 'js-yaml'

import { type Config as _Config, validateConfig } from './schema.js'

import type { ConfigFormat } from './schema.js'

/**
 * CONFIG-T03-AC03: Config template with inline documentation
 *
 * This template includes comments explaining each configuration option.
 * The comments are YAML-compatible and will be preserved in YAML output.
 */
const CONFIG_TEMPLATE_WITH_DOCS = `# iMessage Timeline Configuration File
# Generated by: imessage-timeline init
#
# This file configures the iMessage message export and enrichment pipeline.
# Supports both YAML and JSON formats with environment variable substitution.

# Schema version (for future migrations)
version: "1.0"

# ============================================================================
# Attachment Resolution
# ============================================================================

# Directories to search for message attachments
# Multiple paths supported; first match wins
# Environment variable expansion supported: \${HOME}/Library/Messages
attachmentRoots:
  - "~/Library/Messages/Attachments"
  # Add additional search paths if needed:
  # - "/path/to/imazing/backup/attachments"

# ============================================================================
# Gemini AI Configuration
# ============================================================================

gemini:
  # Google Gemini API key (required for AI enrichment)
  # Get your key from: https://makersuite.google.com/app/apikey
  # Environment variable recommended for security: \${GEMINI_API_KEY}
  apiKey: "\${GEMINI_API_KEY}"

  # Gemini model to use for enrichment
  # Options: gemini-1.5-pro, gemini-1.5-flash
  # Default: gemini-1.5-pro (more accurate, slower)
  model: "gemini-1.5-pro"

  # Delay between API calls (milliseconds)
  # Prevents rate limiting; adjust based on your quota
  # Free tier: 60 requests/minute = 1000ms delay minimum
  # Default: 1000 (1 second)
  rateLimitDelay: 1000

  # Maximum retries for failed API calls
  # Applies exponential backoff with jitter
  # Range: 0-10
  # Default: 3
  maxRetries: 3

# ============================================================================
# Firecrawl Configuration (Optional)
# ============================================================================

# firecrawl:
#   # Firecrawl API key for enhanced link scraping (optional)
#   # Get your key from: https://firecrawl.dev
#   # Falls back to built-in scrapers if not provided
#   apiKey: "\${FIRECRAWL_API_KEY}"
#
#   # Enable/disable Firecrawl for link enrichment
#   # Default: true (if apiKey provided)
#   enabled: true

# ============================================================================
# Enrichment Pipeline Configuration
# ============================================================================

enrichment:
  # Enable image analysis (captions, descriptions via Gemini Vision)
  # HEIC/TIFF files converted to JPG for analysis
  # Default: true
  enableVisionAnalysis: true

  # Enable audio transcription (voice memos, audio messages)
  # Includes timestamps, speaker detection, and summaries
  # Default: true
  enableAudioTranscription: true

  # Enable link context extraction (titles, summaries, metadata)
  # Uses Firecrawl if configured, falls back to built-in scrapers
  # Default: true
  enableLinkEnrichment: true

  # Cache directory for image previews (HEIC/TIFF → JPG)
  # Prevents redundant conversions on re-runs
  # Default: ./.cache/images
  imageCacheDir: "./.cache/images"

  # Checkpoint interval (messages per checkpoint)
  # Lower = more frequent checkpoints = safer but slower
  # Higher = faster but more work lost on interruption
  # Range: 1-10000
  # Default: 100
  checkpointInterval: 100

  # Force refresh of existing enrichments
  # If true, re-enriches messages even if already enriched
  # Default: false (skip already-enriched messages)
  forceRefresh: false

# ============================================================================
# Markdown Rendering Configuration
# ============================================================================

render:
  # Group messages by time-of-day (Morning, Afternoon, Evening)
  # If false, renders as flat chronological list
  # Default: true
  groupByTimeOfDay: true

  # Render replies as nested blockquotes under parent message
  # If false, renders as flat list with reply indicators
  # Default: true
  renderRepliesAsNested: true

  # Render tapbacks (reactions) as emoji (❤️, 😂, etc.)
  # If false, renders as text descriptions
  # Default: true
  renderTapbacksAsEmoji: true

  # Maximum nesting depth for nested replies
  # Prevents infinite recursion in circular reply chains
  # Range: 1-100
  # Default: 10
  maxNestingDepth: 10
`

/**
 * CONFIG-T03-AC03: Generate JSON template with comments
 *
 * JSON doesn't support inline comments, so we use a separate
 * structure with documentation as values.
 */
const CONFIG_TEMPLATE_JSON = {
	_comment: 'iMessage Timeline Configuration File',
	_generated: 'Generated by: imessage-timeline init',
	_docs: 'Full documentation: https://github.com/your-repo/imessage-timeline',

	version: '1.0',

	attachmentRoots: ['~/Library/Messages/Attachments'],

	gemini: {
		_comment: 'Get API key from: https://makersuite.google.com/app/apikey',
		apiKey: '${GEMINI_API_KEY}',
		model: 'gemini-1.5-pro',
		rateLimitDelay: 1000,
		maxRetries: 3,
	},

	enrichment: {
		enableVisionAnalysis: true,
		enableAudioTranscription: true,
		enableLinkEnrichment: true,
		imageCacheDir: './.cache/images',
		checkpointInterval: 100,
		forceRefresh: false,
	},

	render: {
		groupByTimeOfDay: true,
		renderRepliesAsNested: true,
		renderTapbacksAsEmoji: true,
		maxNestingDepth: 10,
	},
}

/**
 * CONFIG-T03-AC02: Generate config file content in specified format
 *
 * @param format - Output format ('json' or 'yaml')
 * @returns Formatted config file content as string
 *
 * @example
 * ```typescript
 * const yamlContent = generateConfigContent('yaml')
 * const jsonContent = generateConfigContent('json')
 * ```
 */
export function generateConfigContent(format: ConfigFormat): string {
	if (format === 'yaml') {
		// Return YAML template with comments preserved
		return CONFIG_TEMPLATE_WITH_DOCS
	}
	// Return formatted JSON with indentation
	return `${JSON.stringify(CONFIG_TEMPLATE_JSON, null, 2)}\n`
}

/**
 * CONFIG-T03-AC04: Check if config file exists at path
 *
 * @param filePath - Path to check
 * @returns True if file exists and is readable
 */
export async function configFileExists(filePath: string): Promise<boolean> {
	try {
		await access(filePath, constants.R_OK)
		return true
	} catch {
		return false
	}
}

/**
 * CONFIG-T03-AC05: Validate generated config content
 *
 * Parses the generated content and validates against schema
 * to ensure the template produces valid config.
 *
 * @param content - Generated config content
 * @param format - Format of content ('json' | 'yaml')
 * @returns Validation result
 */
export function validateGeneratedConfig(
	content: string,
	format: ConfigFormat,
): { valid: boolean; errors?: string[] } {
	try {
		let parsed: unknown

		if (format === 'json') {
			parsed = JSON.parse(content)
		} else {
			parsed = yaml.load(content)
		}

		// Validate against schema (will throw if invalid)
		// Note: This will fail validation because ${GEMINI_API_KEY} is a placeholder
		// In production, we document this expected behavior
		validateConfig(parsed)

		return { valid: true }
	} catch (error) {
		if (error instanceof Error) {
			return {
				valid: false,
				errors: [error.message],
			}
		}
		return {
			valid: false,
			errors: ['Unknown validation error'],
		}
	}
}

/**
 * CONFIG-T03-AC01: Generate config file at specified path
 *
 * Implements the core config generation logic with:
 * - Format selection (YAML/JSON)
 * - Overwrite protection
 * - Content validation
 *
 * @param options - Generation options
 * @param options.filePath - Output file path
 * @param options.format - File format ('json' | 'yaml')
 * @param options.force - Overwrite existing file without prompt
 * @returns Success/failure result
 *
 * @example
 * ```typescript
 * // Generate YAML config (default)
 * await generateConfigFile({ filePath: './imessage-config.yaml' })
 *
 * // Generate JSON config
 * await generateConfigFile({
 *   filePath: './imessage-config.json',
 *   format: 'json'
 * })
 *
 * // Force overwrite
 * await generateConfigFile({
 *   filePath: './imessage-config.yaml',
 *   force: true
 * })
 * ```
 */
export async function generateConfigFile(options: {
	filePath: string
	format?: ConfigFormat
	force?: boolean
}): Promise<{ success: boolean; message: string; filePath: string }> {
	const { filePath, format = 'yaml', force = false } = options

	// CONFIG-T03-AC04: Check for existing file
	const exists = await configFileExists(filePath)
	if (exists && !force) {
		return {
			success: false,
			message: `Config file already exists at ${filePath}. Use --force to overwrite.`,
			filePath,
		}
	}

	// CONFIG-T03-AC02 & AC03: Generate content with docs
	const content = generateConfigContent(format)

	// Write file
	try {
		await writeFile(filePath, content, 'utf-8')

		return {
			success: true,
			message: `✅ Generated ${format.toUpperCase()} config at ${filePath}`,
			filePath,
		}
	} catch (error) {
		return {
			success: false,
			message: `Failed to write config file: ${
				error instanceof Error ? error.message : String(error)
			}`,
			filePath,
		}
	}
}

/**
 * Get default config file path for a given format
 *
 * @param format - Desired format ('json' | 'yaml')
 * @returns Default file path
 */
export function getDefaultConfigPath(format: ConfigFormat): string {
	return format === 'yaml' ? './imessage-config.yaml' : './imessage-config.json'
}
